services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=hunterpgdb'
      - 'POSTGRES_PASSWORD=hunt3r'
      - 'POSTGRES_USER=hunt3r'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432'
