spring:
  application:
    name: hunterpgdb
  datasource:
    url: jdbc:postgresql://localhost:5432/hunterpgdb
    username: hunt3r
    password: hunt3r
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4
  vectorstore:
    pgvector:
    index-type: HNSW
    distance-type: COSINE_DISTANCE
    dimensions: 1536
    batching-strategy: TOKEN_COUNT # Optional: Controls how documents are batched for embedding
    max-document-batch-size: 10000 # Optional: Maximum number of documents per batch